### ISSUE TITLE
CNAs must keep up with JSON schema changes

### ISSUE THREAD

**Issue by eoinwm** [zmanion/CVE#12]
CNAs are responsible for staying up-to-date JSON schema and record format standards/must maintain compatibility with the current JSON schema

**Comment by zmanion** [comment]
Covered in draft2-working [4.5.5](https://docs.google.com/document/d/12jf-CYn9fH2044YyF1fVf0pRaW4o48JVEKVCArEN5zU/edit#heading=h.q5bhml9nf007).
